packageExtensions:
  babel-plugin-relay@*:
    dependencies:
      "@babel/runtime": ^7.13.10
  consolidate@*:
    dependencies:
      handlebars: ^4.7.7
  html-webpack-plugin@*:
    dependencies:
      loader-utils: ^2.0.0
  relay-compiler@*:
    dependencies:
      relay-compiler-language-typescript: ^14.0.0
      relay-config: ^11.0.1

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-bundle.cjs
    spec: "https://yarnplugins.com/bundle"
  - path: .yarn/plugins/@yarnpkg/plugin-push.cjs
    spec: "https://yarnplugins.com/push"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
